import type { Metadata } from "next";
import { Kreon, Inter } from "next/font/google";
import "./globals.css";

const kreon = Kreon({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${kreon.className} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
