import type { Metadata } from "next";
import { Kreon } from "next/font/google";
import "./globals.css";

const kreon = Kreon({
  variable: "--font-kreon",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kreon.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
